{% set name = "mako-rust" %}
{% set version = "0.9.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/umijs/mako/archive/v{{ version }}.tar.gz
  sha256: cc90971c13dc12bfb29f3f7d8119e9eaca5288e38af3daab5316e290e2e4d8bd

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make
    - cargo-bundle-licenses

test:
  commands:
    - mako --help

about:
  home: https://github.com/umijs/mako
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: An extremely fast, production-grade web bundler based on Rust.
  dev_url: https://github.com/umijs/mako

extra:
  recipe-maintainers:
    - danielnachun
