{% set name = "mako-rust" %}
{% set version = "0.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/umijs/mako/archive/v{{ version }}.tar.gz
  sha256: 8c4722d0f9bdfc6bd875aac64aac0fae5bbad7185c15832f22002736fac0c597

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make
    - cargo-bundle-licenses

test:
  commands:
    - mako --help

about:
  home: https://github.com/umijs/mako
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: An extremely fast, production-grade web bundler based on Rust.
  dev_url: https://github.com/umijs/mako

extra:
  recipe-maintainers:
    - danielnachun
