{% set name = "mako-rust" %}
{% set version = "0.9.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/umijs/mako/archive/v{{ version }}.tar.gz
  sha256: 0c4f92fd269af55976305c693fae5f1d9fb78bb7e22fa68eaaae1e300a1dfe5a

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make
    - cargo-bundle-licenses

test:
  commands:
    - mako --help

about:
  home: https://github.com/umijs/mako
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: An extremely fast, production-grade web bundler based on Rust.
  dev_url: https://github.com/umijs/mako

extra:
  recipe-maintainers:
    - danielnachun
