context:
  version: "1.4.15"

package:
  name: mako-rust
  version: ${{ version }}

source:
  url: https://github.com/umijs/mako/archive/v${{ version }}.tar.gz
  sha256: f069451317b235e776603e63798008dddfb25ea77ce0090e2703ccd86f5605d6

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - make
    - cargo-bundle-licenses

tests:
  - script:
      - mako --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: An extremely fast, production-grade web bundler based on Rust.
  homepage: https://github.com/umijs/mako
  repository: https://github.com/umijs/mako

extra:
  recipe-maintainers:
    - danielnachun
