context:
  version: "0.11.4"

package:
  name: mako-rust
  version: ${{ version }}

source:
  url: https://github.com/umijs/mako/archive/${{ version }}.tar.gz
  sha256: 5203edcb4897e3a3a84b697166f09e2b99429402da356011479e37e9b472857a

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - make
    - cargo-bundle-licenses

tests:
  - script:
      - mako --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: An extremely fast, production-grade web bundler based on Rust.
  homepage: https://github.com/umijs/mako
  repository: https://github.com/umijs/mako

extra:
  recipe-maintainers:
    - danielnachun
